/ / 查询中间表SQL语句
SELECT TELNETCONN.ID AS ID,
  TELNETCONN.RECORDTIME_TELNETCONN AS RECORDTIME_TELNETCONN,
  TELNETCONN.TELNETID AS OTHER_ID,
  TELNETCONN.CLIENTIPLOWER AS FROM_IP,
  TELNETCONN.CLIENTPORT AS FROM_PORT,
  TELNETCONN.SERVERIPLOWER AS TARGET_IP,
  TELNETCONN.SERVERPORT AS TARGET_PORT,
  TELNETCONN.TRANSSTARTTIME AS LOGIN_TIME,
  TELNETCONN.QUITTIME AS LOGOUT_TIME,
  TELNETCONN.CONNECTIONTIME AS CONNECTION_TIME,
  TELNETCONN.LOGINFLAG AS LOGIN_FLAG,
  TELNETCONN.LOGINUSER AS LOGIN_USER,
  TELNETCONN.KERNEL AS KERNEL,
  TELNETCONN.CLIENTOS AS CLIENT_OS,
  TELNETCONN.STATUS AS STATUS,
  TELNETCONN.APM_FLAG AS APM_FLAG
FROM PROBE.TBL_PERF_TELNETCONN AS TELNETCONN
WHERE RECORDTIME_TELNETCONN > 1697179114
ORDER BY RECORDTIME_TELNETCONN
LIMIT 10