CREATE TABLE PROBE.TBL_PERF_FTP (
  ID VARCHAR NOT NULL,
  RECORDTIME_FTP BIGINT,
  FTPID VARCHAR,
  CLIENTIPLOWER BIGINT,
  CLIENTPORT INTEGER,
  SERVERIPLOWER BIGINT,
  SERVERPORT INTEGER,
  USERLOGINNAME VARCHAR,
  USERLOGINPWD VARCHAR,
  LOGINFLAG VARCHAR,
  DOWNFILECOUNT INTEGER,
  UPFILECOUNT INTEGER,
  STARTTIME BIGINT,
  APM_FLAG VARCHAR
);