SELECT
  /*+ USE_SORT_MERGE_JOIN */
  DMSQL.ID AS ID,
  DMSQL.RECORDTIME_DMSQL AS RECORDTIME_DMSQL,
  DMSQL.ID AS DATA_BASE_EXEC_ID,
  DMSQL.OPERATINGTABLE AS TABLE_NAME,
  DMSQL.COMTYPE AS SQL_TYPE,
  DMSQL.REQSTARTTIME AS START_EXEC_TIME,
  DMSQL.EXECUTIONTIME AS EXEC_TIME,
  DMSQL.AFFECTSROWS AS AFFECT_ROWS,
  DMSQL.SQLSTATUS AS EXEC_RESULT,
  DMSQL.SQLRESDATA AS SEARCH_RESULT,
  DMSQL.REQUESTERRINFO AS FAIL_INFO,
  DMSQL.REFUSECODE AS FAIL_CODE,
  DMSQL.SQLSTATEMENT AS SQL,
  DMSQL.REQPACKETSIZE AS REQ_BYTES,
  DMSQL.RSPPACKETSIZE AS RSP_BYTES,
  DMSQL.REQPACKETNUM AS REQ_PACKETS,
  DMSQL.RSPPACKETNUM AS RSP_PACKET,
  DMSQL.RETRANSMITREQ AS RETRANS_REQKTS,
  DMSQL.RETRANSMITC AS RETRANS_REQBYTES,
  DMSQL.RETRANSMITRES AS RETRANS_PSPPKTS,
  DMSQL.RETRANSMITS AS RETRANS_PSPBYTES,
  DMSQL.SQLREQTIME AS REQ_TIME,
  DMSQL.SQLRSPTIME AS RSP_TIME,
  DMSQL.APMFLAG AS APM_FLAG,
  DAMENG.CLIENTIPLOWER AS FROM_IP,
  DAMENG.CLIENTPORT AS FROM_PORT,
  DAMENG.SERVERIPLOWER AS TARGET_IP,
  DAMENG.SERVERPORT AS TARGET_PORT,
  DAMENG.USERNAME AS DATA_BASE_ACCOUNT,
  DAMENG.LOGINDATABASE AS INSTANCE,
  DAMENG.VERSION AS DATA_BASE_VERSION,
  DAMENG.SESSIONID AS SESSION_ID
FROM PROBE.TBL_PERF_DAMENGSQL_TEST AS DMSQL
  INNER JOIN PROBE.TBL_PERF_DAMENG_TEST AS DAMENG ON DMSQL.SESSIONID = DAMENG.SESSIONID
WHERE RECORDTIME_DMSQL > 1698746908
ORDER BY RECORDTIME_DMSQL
LIMIT 10