/ / 查询中间表SQL语句
SELECT TELNETRRPAIR.ID AS ID,
  TELNETRRPAIR.RECORDTIME_TELNETRRPAIR AS RECORDTIME_TELNETRRPAIR,
  TELNETRRPAIR.CLIENTIPLOWER AS FROM_IP,
  TELNETRRPAIR.CLIENTPORT AS FROM_PORT,
  TELNETRRPAIR.SERVERIPLOWER AS TARGET_IP,
  TELNETRRPAIR.SERVERPORT AS TARGET_PORT,
  TELNETRRPAIR.REQTYPE AS EXEC_COMMOND,
  TELNETRRPAIR.RSPTYPE AS EXEC_RESULT,
  TELNETRRPAIR.TELNETID AS SESSION_ID,
  TELNETRRPAIR.RSPSTATUS AS FAILED_INFO,
  TELNETRRPAIR.REQBYTE AS REQ_BYTES,
  TELNETRRPAIR.RSPBYTE AS RSP_BYTES,
  TELNETRRPAIR.REQPKTCNT AS REQ_PACKETS,
  TELNETRRPAIR.RESPKTCNT AS RSP_PACKET,
  TELNETRRPAIR.REQRETRANSCOUNT AS RETRANS_REQKTS,
  TELNETRRPAIR.REQRETRANSBYTE AS RETRANS_REQBYTES,
  TELNETRRPAIR.RSPRETRANSCOUNT AS RETRANS_PSPPKTS,
  TELNETRRPAIR.RSPRETRANSBYTE AS RETRANS_PSPBYTES,
  TELNETRRPAIR.REQTIME AS REQ_TIME,
  TELNETRRPAIR.RSPTIME AS RSP_TIME,
  TELNETRRPAIR.APM_FLAG AS APM_FLAG
FROM PROBE.TBL_PERF_TELNETRRPAIR AS TELNETRRPAIR
WHERE RECORDTIME_TELNETRRPAIR > 1698306356
ORDER BY RECORDTIME_TELNETRRPAIR
LIMIT 10