SELECT PAIR.ID AS ID,
  PAIR.RECORDTIME_KINGBASE AS RECORDTIME_KINGBASE,
  PAIR.BUSINESSID AS OTHER_ID,
  PAIR.CLIENTIPLOWER AS FROM_IP,
  PAIR.CLIENTPORT AS FROM_PORT,
  PAIR.SERVERIPLOWER AS TARGET_IP,
  PAIR.SERVERPORT AS TARGET_PORT,
  PAIR.LOGINUSER AS DATA_BASE_ACCOUNT,
  PAIR.LOGINDATABASE AS DATA_BASE_NAME,
  PAIR.VERSION AS DATA_BASE_VERSION,
  PAIR.LOGINTIME AS LOGIN_TIME,
  PAIR.LOGINSTATUS AS LOGIN_STATUS,
  PAIR.LOGINFAILEDINFO AS LOGIN_FAILED_INFO,
  PAIR.LOGINERRCODE AS LOGIN_ERR_CODE,
  PAIR.LOGINMETHOD AS LOGIN_TYPE,
  PAIR.APMFLAG AS APM_FLAG,
  PAIR.LOGINSUCCESSTIME AS LOGIN_SUCCESS_TIME
FROM PROBE.TBL_PERF_KINGBASEBIZ AS PAIR
WHERE RECORDTIME_KINGBASE > 0
ORDER BY RECORDTIME_KINGBASE
LIMIT 10