SELECT
  /*+ USE_SORT_MERGE_JOIN */
  PAIR.ID AS ID,
  PAIR.RECORDTIME_FTPRRPAIR AS RECORDTIME_FTPRRPAIR,
  PAIR.CLIENTIPLOWER AS FROM_IP,
  PAIR.CLIENTPORT AS FROM_PORT,
  PAIR.SERVERIPLOWER AS TARGET_IP,
  PAIR.SERVERPORT AS TARGET_PORT,
  PAIR.REQTYPE AS COMMOND,
  PAIR.RSPTYPE AS RSP_CODE,
  PAIR.FTPID AS SESSION_ID,
  PAIR.REQBYTE AS REQ_BYTES,
  PAIR.RSPBYTE AS RSP_BYTES,
  PAIR.REQPKTS AS REQ_PACKETS,
  PAIR.RSPPKTS AS RSP_PACKET,
  PAIR.RSQRETRANSBYTE AS RETRANS_PSPBYTES,
  PAIR.REQRETRANSBYTE AS RETRANS_REQBYTES,
  PAIR.REQRETRANSCOUNT AS RETRANS_REQKTS,
  PAIR.RSPRETRANSCOUNT AS RETRANS_PSPPKTS,
  PAIR.REQTIME AS REQ_TIME,
  PAIR.RSPTIME AS RSP_TIME,
  PAIR.APM_FLAG AS APM_FLAG,
  PAIR2.FILENAME AS FILE_NAME,
  PAIR2.FILESIZE AS FILE_SIZE,
  PAIR2.FILEDIRNAME AS FILE_PATH,
  PAIR2.TRANRATE AS TRANS_RATE,
  PAIR2.TRANMODE AS CONN_MODE,
  PAIR2.SERVERPORT AS CONTROL_PORT,
  PAIR2.TRANTYPE AS TRANS_DIRECTION,
  PAIR2.FILEPATH AS FILE_DETAIL,
  PAIR2.FILEDOWN_UPSTARTTIME AS FILEDOWN_UPSTARTTIME,
  PAIR2.FILEDOWN_UPENDTIME AS FILEDOWN_UPENDTIME
FROM PROBE.TBL_PERF_FTPRPAIR AS PAIR
  LEFT JOIN PROBE.TBL_PERF_FTPDATA AS PAIR2 ON PAIR.FTPID = PAIR2.FTPID
WHERE RECORDTIME_FTPRRPAIR >{ OFFSET }
ORDER BY RECORDTIME_FTPRRPAIR