CREATE TABLE PROBE.TBL_PERF_FTPDATA (
  ID VARCHAR NOT NULL,
  RECORDTIME_FTPDATA BIGINT,
  FILENAME VARCHAR,
  FILESIZE BIGINT,
  FILEDIRNAME VARCHAR,
  TRANRATE FLOAT,
  SERVERPORT VARCHAR,
  TRANTYPE INTEGER,
  FILEPATH VARCHAR,
  FTPID VARCHAR,
  FILEDOWN_UPSTARTTIME BIGINT,
  FILEDOWN_UPENDTIME BIGINT,
  TRANMODE VARCHAR
);