SELECT PAIR.ID AS ID,
  PAIR.RECORDTIME_FTP AS RECORDTIME_FTP,
  PAIR.FTPID AS OTHER_ID,
  PAIR.CLIENTIPLOWER AS FROM_IP,
  PAIR.CLIENTPORT AS FROM_PORT,
  PAIR.SERVERIPLOWER AS TARGET_IP,
  PAIR.SERVERPORT AS TARGET_PORT,
  PAIR.USERLOGINNAME AS USER_LOGIN_NAME,
  PAIR.USERLOGINPWD AS USER_LOGIN_P_W_D,
  PAIR.LOGINFLAG AS LOGIN_FLAG,
  PAIR.DOWNFILECOUNT AS DOWN_FILE_COUNT,
  PAIR.UPFILECOUNT AS UP_FILE_COUNT,
  PAIR.STARTTIME AS LOGIN_TIME,
  PAIR.APM_FLAG AS APM_FLAG
FROM PROBE.TBL_PERF_FTP AS PAIR
WHERE RECORDTIME_FTP > ${ OFFSET }
ORDER BY RECORDTIME_FTP
