SELECT
  /*+ USE_SORT_MERGE_JOIN */
  PAIR.RECORDTIME_MYSQLRPAIR AS RECORDTIME_MYSQLRPAIR,
  PAIR.ID AS DATA_BASE_EXEC_ID,
  PAIR.REQIPLOWER AS FROM_IP,
  PAIR.REQPORT AS FROM_PORT,
  PAIR.RSPIPLOWER AS TARGET_IP,
  PAIR.RSPPORT AS TARGET_PORT,
  PAIR.OPERATINGDB AS DATA_BASE_NAME,
  PAIR.OPERATINGTABLE AS TABLE_NAME,
  PAIR.REQTYPE AS SQL_TYPE,
  PAIR.REQSTARTTIME AS START_EXEC_TIME,
  PAIR.EXECUTIONTIME AS EXEC_TIME,
  PAIR.AFFECTSROWS AS AFFECT_ROWS,
  PAIR.EXECUTIONRESULT AS EXEC_RESULT,
  PAIR.SQLRESDATA AS SEARCH_RESULT,
  PAIR.REFUSECODE AS FAIL_CODE,
  PAIR.REQUESTERRINFO AS FAIL_INFO,
  PAIR.SQLSTATEMENT AS SQL,
  PAIR.BUSINESSID AS SESSION_ID,
  PAIR.REQPACKETSIZE AS REQ_BYTES,
  PAIR.RSPPACKETSIZE AS RSP_BYTES,
  PAIR.REQPACKETNUM AS REQ_PACKETS,
  PAIR.RSPPACKETNUM AS RSP_PACKET,
  PAIR.RETRANSMITREQ AS RETRANS_REQKTS,
  PAIR.RETRANSMITREQBYTE AS RETRANS_REQBYTES,
  PAIR.RETRANSMITRES AS RETRANS_PSPPKTS,
  PAIR.RETRANSMITRESBYTE AS RETRANS_PSPBYTES,
  PAIR.RSPENDTIME AS RSP_TIME,
  PAIR.APM_FLAG AS APM_FLAG,
  PAIR.WARNING_COUNT AS WARNING_COUNT,
  BIZ.LOGINUSER AS DATA_BASE_ACCOUNT,
  BIZ.VERSION AS DATA_BASE_VERSION
FROM PROBE.TBL_PERF_MYSQLRRPAIR AS PAIR
  INNER JOIN PROBE.TBL_PERF_MYSQLBIZ AS BIZ ON PAIR.BUSINESSID = BIZ.BUSINESSID
WHERE RECORDTIME_MYSQLRPAIR > 1698824992
ORDER BY RECORDTIME_MYSQLRPAIR
LIMIT 10