CREATE TABLE PROBE.TBL_PERF_TELNETCONN (
  ID VARCHAR NOT NULL,
  RECORDTIME_TELNETCONN BIGINT,
  TELNETID BIGINT,
  CLIENTIPLOWER BIGINT,
  CLIENTPORT INTEGER,
  SERVERIPLOWER BIGINT,
  SERVERPORT INTEGER,
  TRANSSTARTTIME BIGINT,
  QUITTIME BIGINT,
  CONNECTIONTIME BIGINT,
  LOGINFLAG VARCHAR,
  LOGINUSER VARCHAR,
  KERNEL VARCHAR,
  CLIENTOS VARCHAR,
  STATUS INTEGER,
  APM_FLAG VARCHAR
);